# Generated by Django 4.1.7 on 2023-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilettts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.TextField(verbose_name='kuda')),
                ('nam', models.TextField(verbose_name='otkuda')),
                ('name', models.DateTimeField()),
            ],
        ),
    ]
