# Generated by Django 4.1.7 on 2023-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bilettts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilettts',
            name='nambers',
            field=models.CharField(default=1, max_length=1, verbose_name=' жд (1), самолет (2), автобус 3)'),
            preserve_default=False,
        ),
    ]
