# Generated by Django 4.1.7 on 2023-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bilettts_nambers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilettts',
            name='nambers',
        ),
        migrations.AddField(
            model_name='bilettts',
            name='kategoria',
            field=models.TextField(default=1, verbose_name='жд, самолет, автобус'),
            preserve_default=False,
        ),
    ]
